import Foundation
import WordwellDomain

/// The 3,000 most frequent English words, generated by `Tools/build_common_words.py` into `CommonWords3000.json`.
/// A missing or broken file yields an empty list; the UI then shows an unavailable state.
public enum CommonWordsCatalog {
    public static func load() -> [CommonWord] {
        guard let url = Bundle.module.url(forResource: "CommonWords3000", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let ids = try? JSONDecoder().decode([String].self, from: data) else { return [] }
        return ids.enumerated().compactMap { CommonWord(id: $1, rank: $0 + 1) }
    }

    /// Entry id -> topic id, generated by `Tools/build_common_topics.py`. Missing file means no grouping.
    public static func topics() -> [String: String] {
        guard let url = Bundle.module.url(forResource: "CommonWordTopics", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let map = try? JSONDecoder().decode([String: String].self, from: data) else { return [:] }
        return map
    }
}
